name: 'Hello World'
description: 'Greet someone'
inputs:
  python_version:
    required: true
    default: '3.8'
  streamlit_version:
    required: true
    default: '1.25.0'
  streamlit_path:
    default: ''

runs:
  using: "composite"
  steps:
    - name: Build docker images
      run: ./dev.py e2e-build-images "--streamlit-version=${{ env.STREAMLIT_VERSION }}" "--python-version=${{ env.PYTHON_VERSION }}"
      working-directory: ${{ github.action_path }}/../../../
      shell: bash
      env:
        STREAMLIT_VERSION: ${{ inputs.streamlit_version }}
        PYTHON_VERSION: ${{ inputs.python_version }}

    - name: Run e2e tests
      run: ./dev.py e2e-run-tests "--streamlit-version=${{ env.STREAMLIT_VERSION }}" "--python-version=${{ env.PYTHON_VERSION }}"
      shell: bash
      working-directory: ${{ github.action_path }}/../../../
      env:
        STREAMLIT_VERSION: ${{ inputs.streamlit_version }}
        PYTHON_VERSION: ${{ inputs.python_version }}
