name: E2E tests
description: Run e2e tests for templates and examples in separate docker images

inputs:
  python_version:
    description: 'Python version'
    required: true
    default: '3.8'
  streamlit_version:
    description: 'Streamlit version'
    required: false
    default: ''
  streamlit_wheel_file:
    description: 'Streamlit wheel file'
    required: false
    default: ''


runs:
  using: "composite"
  steps:
    - name: Build docker images
      shell: bash
      run: |
        if [ -n "${{ inputs.streamlit_version }}" ]; then
          ./dev.py e2e-build-images "--streamlit-version=${{ inputs.streamlit_version }}" "--python-version=${{ inputs.python_version }}"
        elif [ -n "${{ inputs.streamlit_wheel_file }}" ]; then
          ./dev.py e2e-build-images "--streamlit-wheel-file=${{ inputs.streamlit_wheel_file }}" "--python-version=${{ inputs.python_version }}"
        else
          echo "One and exactly one input is required: streamlit_version, streamlit_wheel_file"
          exit 1
        fi
      working-directory: ${{ github.action_path }}/../../../

    - name: Check prerequisite
      run: |
        One and exactly one input is required: streamlit_version, streamlit_wheel_file
        exit 1
      if: inputs.streamlit_version == '' && inputs.streamlit_wheel_file == ''
      shell: bash

    - name: Run e2e tests
      run: ./dev.py e2e-run-tests "--streamlit-version=${{ env.STREAMLIT_VERSION }}" "--python-version=${{ env.PYTHON_VERSION }}"
      shell: bash
      working-directory: ${{ github.action_path }}/../../../
      env:
        STREAMLIT_VERSION: ${{ inputs.streamlit_wheel_file == '' &&  inputs.streamlit_version || 'custom' }}
        PYTHON_VERSION: ${{ inputs.python_version }}
