name: E2E tests

description: Running e2e tests for templates and examples in separate docker images

inputs:
  streamlit_version:
    description: 'Streamlit version'
    required: true
  python_version:
    description: 'Python version'
    required: true


runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@7703e82fbced3d0c9eec08dff4429c023a5fd9a9 # v2.9.1

    - name: Build docker images
      shell: bash
      run: |
        ./dev.py e2e-build-images "--streamlit-version=${{ inputs.streamlit_version }}" "--python-version=${{ inputs.python_version }}"

    - name: Run e2e tests
      shell: bash
      run: |
        ./dev.py e2e-run-tests "--streamlit-version=${{ inputs.streamlit_version }}" "--python-version=${{ inputs.python_version }}"