name: E2E tests

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    status:
      - success

jobs:
  run-dockerized-e2e-tests:
    if: startsWith(env.NODE_VERSION, '19.x')
    runs-on: ubuntu-latest

    name: E2E tests / streamlit_version=${{ matrix.streamlit_version }}  / component_lib_version=${{ matrix.component_lib_version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@7703e82fbced3d0c9eec08dff4429c023a5fd9a9 # v2.9.1

      - name: Build docker images
        run: ./dev.py e2e-build-images "--streamlit-version=${{ env.STREAMLIT_VERSION }}" "--python-version=${{ env.PYTHON_VERSION }}"

      - name: Run e2e tests
        run: ./dev.py e2e-run-tests "--streamlit-version=${{ env.STREAMLIT_VERSION }}" "--python-version=${{ env.PYTHON_VERSION }}"