name: E2E tests

on:
  workflow_call:

jobs:
  run-dockerized-e2e-tests:
    runs-on: ubuntu-latest

    name: E2E tests / streamlit_version=${{ matrix.streamlit_version }}  / component_lib_version=${{ matrix.component_lib_version }}

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@7703e82fbced3d0c9eec08dff4429c023a5fd9a9 # v2.9.1

      - name: Build docker images
        run: ./dev.py e2e-build-images "--streamlit-version=${{ inputs.streamlit_version }}" "--python-version=${{ inputs.python_version }}"

      - name: Run e2e tests
        run: ./dev.py e2e-run-tests "--streamlit-version=${{ inputs.streamlit_version }}" "--python-version=${{ inputs.python_version }}"